{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"machine_shape":"hm","gpuType":"V100","authorship_tag":"ABX9TyM2+RFCQ9f0dadd9h9uTR9d"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"},"accelerator":"GPU"},"cells":[{"cell_type":"markdown","source":["# Sainfoin Seed Classification FasterRCNN Model"],"metadata":{"id":"ZN2WkkTRV5bZ"}},{"cell_type":"markdown","source":["### For Colab Users\n","Run the code cell below to mount your Google Drive. Change the `BASE_DIR` variable to the folder location of the cloned GitHub folder relative to your Google Drive, so something along the lines of 'drive/MyDrive/path/to/dir/repo_folder'."],"metadata":{"id":"VOCEEVboV-cy"}},{"cell_type":"code","execution_count":1,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"8iR9c3UQV1qY","executionInfo":{"status":"ok","timestamp":1694122306504,"user_tz":240,"elapsed":1508,"user":{"displayName":"Bo Meyering","userId":"12820085305614794448"}},"outputId":"76f6e048-bcf8-4526-ee7a-ef7c48a9a80d"},"outputs":[{"output_type":"stream","name":"stdout","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"]}],"source":["from google.colab import drive\n","drive.mount('/content/drive')\n","BASE_DIR = 'drive/MyDrive/github_repos/sainfoin_seed_RCNN'\n","%cd -q $BASE_DIR\n"]},{"cell_type":"code","source":["import datetime\n","str(datetime.date.today())"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":35},"id":"5RaxkkWq2rKC","executionInfo":{"status":"ok","timestamp":1694122306506,"user_tz":240,"elapsed":12,"user":{"displayName":"Bo Meyering","userId":"12820085305614794448"}},"outputId":"37b5ab8f-bdf5-4aad-ce77-71cbf0c939b8"},"execution_count":2,"outputs":[{"output_type":"execute_result","data":{"text/plain":["'2023-09-07'"],"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"}},"metadata":{},"execution_count":2}]},{"cell_type":"code","source":["!pip install -r colab_requirements.txt"],"metadata":{"id":"eqYBKHeNWYFW","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1694122310688,"user_tz":240,"elapsed":4192,"user":{"displayName":"Bo Meyering","userId":"12820085305614794448"}},"outputId":"b69a80b4-bc7f-46c1-cecf-b20337670088"},"execution_count":3,"outputs":[{"output_type":"stream","name":"stdout","text":["Requirement already satisfied: torchmetrics in /usr/local/lib/python3.10/dist-packages (from -r colab_requirements.txt (line 1)) (1.1.1)\n","Requirement already satisfied: numpy>1.20.0 in /usr/local/lib/python3.10/dist-packages (from torchmetrics->-r colab_requirements.txt (line 1)) (1.23.5)\n","Requirement already satisfied: torch>=1.8.1 in /usr/local/lib/python3.10/dist-packages (from torchmetrics->-r colab_requirements.txt (line 1)) (2.0.1+cu118)\n","Requirement already satisfied: lightning-utilities>=0.8.0 in /usr/local/lib/python3.10/dist-packages (from torchmetrics->-r colab_requirements.txt (line 1)) (0.9.0)\n","Requirement already satisfied: packaging>=17.1 in /usr/local/lib/python3.10/dist-packages (from lightning-utilities>=0.8.0->torchmetrics->-r colab_requirements.txt (line 1)) (23.1)\n","Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from lightning-utilities>=0.8.0->torchmetrics->-r colab_requirements.txt (line 1)) (4.7.1)\n","Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->torchmetrics->-r colab_requirements.txt (line 1)) (3.12.3)\n","Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->torchmetrics->-r colab_requirements.txt (line 1)) (1.12)\n","Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->torchmetrics->-r colab_requirements.txt (line 1)) (3.1)\n","Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->torchmetrics->-r colab_requirements.txt (line 1)) (3.1.2)\n","Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->torchmetrics->-r colab_requirements.txt (line 1)) (2.0.0)\n","Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.8.1->torchmetrics->-r colab_requirements.txt (line 1)) (3.27.2)\n","Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.8.1->torchmetrics->-r colab_requirements.txt (line 1)) (16.0.6)\n","Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.8.1->torchmetrics->-r colab_requirements.txt (line 1)) (2.1.3)\n","Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.8.1->torchmetrics->-r colab_requirements.txt (line 1)) (1.3.0)\n"]}]},{"cell_type":"markdown","source":["### Module Import"],"metadata":{"id":"4qFjHfEPWp_J"}},{"cell_type":"code","source":["import os\n","import sys\n","import cv2\n","import torch\n","import torchvision\n","import torchmetrics\n","import yaml\n","import time\n","import logging\n","\n","import pandas as pd\n","import numpy as np\n","import albumentations as A\n","\n","from glob import glob\n","from tqdm import tqdm\n","from random import randint\n","from albumentations.pytorch import ToTensorV2\n","from torchmetrics.classification import MulticlassAccuracy, MulticlassJaccardIndex\n","from torchmetrics.detection import IntersectionOverUnion, MeanAveragePrecision\n","from torchvision.models.detection.faster_rcnn import FastRCNNPredictor\n","from torchvision.models.detection.rpn import AnchorGenerator\n","from torchvision.transforms import ToTensor\n","from torchvision.ops import nms\n","from torch.utils.tensorboard import SummaryWriter\n","from torch.utils.data import Dataset, DataLoader\n","from sklearn.model_selection import train_test_split"],"metadata":{"id":"R-pvHmBUWqcm","executionInfo":{"status":"ok","timestamp":1694122317031,"user_tz":240,"elapsed":6348,"user":{"displayName":"Bo Meyering","userId":"12820085305614794448"}}},"execution_count":4,"outputs":[]},{"cell_type":"code","source":[],"metadata":{"id":"3jUvfCUeox0D","executionInfo":{"status":"ok","timestamp":1694122317032,"user_tz":240,"elapsed":7,"user":{"displayName":"Bo Meyering","userId":"12820085305614794448"}}},"execution_count":4,"outputs":[]},{"cell_type":"markdown","source":["### Import Custom Code and Configuration Settings"],"metadata":{"id":"UqhCVcbychuV"}},{"cell_type":"code","source":["sys.path.append('./src')\n","from config import parse_config\n","from loggers import create_logger\n","from model import create_model\n","from transforms import train_transforms, val_transforms, collate_fn\n","from datasets import SeedDataset, dir_sampler\n","from data_splitting import train, val, test\n","from train_val import train_model\n","from config import train_dir, val_dir, test_dir, annotation_dir, chkpt_dir, tensorboard_dir, log_dir\n","from config import device, cores, classes, n_classes, resize_to, n_epochs, batch_size\n","from config import base_name, lr, momentum, gamma\n","\n","\n","\n","# train_dir, val_dir, test_dir, annot_dir,\\\n","# chkpt_dir, tb_dir, log_dir, device, cores,\\\n","# classes, n_classes, resize_to, n_epochs, batch_size,\\\n","# base_name, lr, momentum, gamma = parse_config('config.yml')"],"metadata":{"id":"q6SzsiQfcgyg","executionInfo":{"status":"ok","timestamp":1694122317416,"user_tz":240,"elapsed":389,"user":{"displayName":"Bo Meyering","userId":"12820085305614794448"}}},"execution_count":5,"outputs":[]},{"cell_type":"markdown","source":["### Set up Loggers\n","This cell is meant to be set up only once! If you run it multiple times, you will end up with many duplicates of each logging message."],"metadata":{"id":"C7cp2Ymnnj8Y"}},{"cell_type":"code","source":["logger = create_logger()\n","logger.info('Training notebook started')"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"SX1DsGOZniUb","executionInfo":{"status":"ok","timestamp":1694122317418,"user_tz":240,"elapsed":11,"user":{"displayName":"Bo Meyering","userId":"12820085305614794448"}},"outputId":"78a016f6-8350-4d38-fb73-569685b382ac"},"execution_count":6,"outputs":[{"output_type":"stream","name":"stderr","text":["2023-09-07 21:31:57,220:main_app:INFO: - Training notebook started\n"]}]},{"cell_type":"markdown","source":["### Log System Information"],"metadata":{"id":"Kz1UGm313TQR"}},{"cell_type":"code","source":["os_details = !lsb_release -a\n","os_details = '\\n'.join(os_details)\n","\n","cpu_info = !lscpu\n","cpu_info = '\\n'.join(cpu_info)\n","\n","sys_info = 'Python ' + sys.version\n","\n","headings = ['OS_DETAILS:\\n', 'CPU_INFO:\\n', 'PYTHON KERNEL:\\n']\n","details = [os_details, cpu_info, sys_info]\n","\n","for h, d in zip(headings, details):\n","  logger.info(h + d)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"zkw5fkx7ytg-","executionInfo":{"status":"ok","timestamp":1694122317808,"user_tz":240,"elapsed":398,"user":{"displayName":"Bo Meyering","userId":"12820085305614794448"}},"outputId":"4d515612-9b46-47f7-d87a-f80faad6402c"},"execution_count":7,"outputs":[{"output_type":"stream","name":"stderr","text":["2023-09-07 21:31:57,455:main_app:INFO: - OS_DETAILS:\n","No LSB modules are available.\n","Distributor ID:\tUbuntu\n","Description:\tUbuntu 22.04.2 LTS\n","Release:\t22.04\n","Codename:\tjammy\n","2023-09-07 21:31:57,457:main_app:INFO: - CPU_INFO:\n","Architecture:            x86_64\n","  CPU op-mode(s):        32-bit, 64-bit\n","  Address sizes:         46 bits physical, 48 bits virtual\n","  Byte Order:            Little Endian\n","CPU(s):                  8\n","  On-line CPU(s) list:   0-7\n","Vendor ID:               GenuineIntel\n","  Model name:            Intel(R) Xeon(R) CPU @ 2.00GHz\n","    CPU family:          6\n","    Model:               85\n","    Thread(s) per core:  2\n","    Core(s) per socket:  4\n","    Socket(s):           1\n","    Stepping:            3\n","    BogoMIPS:            4000.29\n","    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mc\n","                         a cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscal\n","                         l nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopo\n","                         logy nonstop_tsc cpuid tsc_known_freq pni pclmulqdq sss\n","                         e3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes \n","                         xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefe\n","                         tch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_ad\n","                         just bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx51\n","                         2f avx512dq rdseed adx smap clflushopt clwb avx512cd av\n","                         x512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_\n","                         clear arch_capabilities\n","Virtualization features: \n","  Hypervisor vendor:     KVM\n","  Virtualization type:   full\n","Caches (sum of all):     \n","  L1d:                   128 KiB (4 instances)\n","  L1i:                   128 KiB (4 instances)\n","  L2:                    4 MiB (4 instances)\n","  L3:                    38.5 MiB (1 instance)\n","NUMA:                    \n","  NUMA node(s):          1\n","  NUMA node0 CPU(s):     0-7\n","Vulnerabilities:         \n","  Itlb multihit:         Not affected\n","  L1tf:                  Mitigation; PTE Inversion\n","  Mds:                   Vulnerable; SMT Host state unknown\n","  Meltdown:              Vulnerable\n","  Mmio stale data:       Vulnerable\n","  Retbleed:              Vulnerable\n","  Spec store bypass:     Vulnerable\n","  Spectre v1:            Vulnerable: __user pointer sanitization and usercopy ba\n","                         rriers only; no swapgs barriers\n","  Spectre v2:            Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBR\n","                         S: Not affected\n","  Srbds:                 Not affected\n","  Tsx async abort:       Vulnerable\n","2023-09-07 21:31:57,458:main_app:INFO: - PYTHON KERNEL:\n","Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]\n"]}]},{"cell_type":"code","source":["# Validate torch device settings\n","if device=='cuda':\n","  try:\n","    assert torch.cuda.is_available(), 'No CUDA device is available.'\n","    logger.info(f\"CUDA device name: {torch.cuda.get_device_name()}\")\n","    logger.info(f\"CUDA device capabilities: {torch.cuda.get_device_capability()}\")\n","    logger.info(f\"CUDA device properties: {torch.cuda.get_device_properties(0)}\")\n","  except AssertionError as e:\n","    logger.warning(e, exc_info=True)\n","    logger.info(\"Overwriting model config and setting device to 'cpu'.\")\n","    device = torch.device('cpu')\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"2JV8Imomtn4j","executionInfo":{"status":"ok","timestamp":1694122317808,"user_tz":240,"elapsed":13,"user":{"displayName":"Bo Meyering","userId":"12820085305614794448"}},"outputId":"d7b3358e-023e-4e64-8acb-3426ec727ce1"},"execution_count":8,"outputs":[{"output_type":"stream","name":"stderr","text":["2023-09-07 21:31:57,481:main_app:INFO: - CUDA device name: Tesla V100-SXM2-16GB\n","2023-09-07 21:31:57,482:main_app:INFO: - CUDA device capabilities: (7, 0)\n","2023-09-07 21:31:57,483:main_app:INFO: - CUDA device properties: _CudaDeviceProperties(name='Tesla V100-SXM2-16GB', major=7, minor=0, total_memory=16150MB, multi_processor_count=80)\n"]}]},{"cell_type":"markdown","source":["### Model Training and Evaluation\n","We will build individual models for each of a range of training sample sizes. The total image dataset is 500 images, thus an 80/20 split on the data results in 400 training images and 100 validation images. The training sizes will be split up as follows:\n","```\n","[20, 40, 80, 200, 400]\n","```\n","with corresponding validation sizes of\n","```\n","[5, 10, 20, 50, 100]\n","```\n","So 5%, 10%, 20%, 50%, and 100% of the total available data for each group"],"metadata":{"id":"4LGnwmx3cgWG"}},{"cell_type":"code","source":["# Set proportion sizes for subsampling the data\n","# sizes = [0.05, 0.1, 0.2, 0.5, 1.0]\n","# sizes = [0.05, 0.5, 1.0]\n","# sizes = [0.5, 1.0]\n","sizes = [1.0]\n","# sizes = [0.5]\n","# Read in all of the image metadata\n","img_data = pd.read_csv('./data/power_analysis/results.csv')\n","print(img_data.head())\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"b3uc-H4n7c_a","executionInfo":{"status":"ok","timestamp":1694122317809,"user_tz":240,"elapsed":11,"user":{"displayName":"Bo Meyering","userId":"12820085305614794448"}},"outputId":"966105c9-0c96-4313-db9d-d33b21f82e9b"},"execution_count":9,"outputs":[{"output_type":"stream","name":"stdout","text":["   Unnamed: 0 img_id   img_name  class                variety     method  \\\n","0           0  12600  12600.jpg  train  Rocky Mountain Remont  HLDP7x35s   \n","1           1  9adc6  9adc6.JPG  train               Shoshone       BT3X   \n","2           2  1cd49  1cd49.jpg  train       AAC Mountainview  HLDP7x35s   \n","3           3  6eb3d  6eb3d.JPG  train               Shoshone       BT3X   \n","4           4  7b24d  7b24d.JPG  train               Shoshone       BT3X   \n","\n","   sample_mass_g  rep  legume_fruit_mass_g  legume_seed_mass_g comments  \n","0              2    7               2.0189               1.569      NaN  \n","1              2    5               2.0131               1.677      NaN  \n","2              4    1               4.0014               2.921      NaN  \n","3              1   10               1.0075               0.887      NaN  \n","4              3    8               3.0066               2.736      NaN  \n"]}]},{"cell_type":"code","source":["img_data.loc[img_data['class']=='train'].shape"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"Va1nKY25ENlA","executionInfo":{"status":"ok","timestamp":1694122317809,"user_tz":240,"elapsed":9,"user":{"displayName":"Bo Meyering","userId":"12820085305614794448"}},"outputId":"ef38e6e7-cd90-4540-d6cc-e3d7fb7697e1"},"execution_count":10,"outputs":[{"output_type":"execute_result","data":{"text/plain":["(400, 11)"]},"metadata":{},"execution_count":10}]},{"cell_type":"code","source":["# Start Tensorboard writer\n","model_config = [\n","    \"model_name:\\tfasterrcnn\",\n","    f\"pretrained:\\tTrue\",\n","    f\"classes:\\t{classes}\",\n","    f\"n_classes:\\t{n_classes}\",\n","    f\"lr:\\t{lr}\",\n","    f\"momentum:\\t{momentum}\",\n","    f\"n_epochs:\\t{n_epochs}\",\n","    f\"batch_size:\\t{batch_size}\",\n","    f\"lr_scheduler_gamma:\\t{gamma}\"\n","]\n","logger.info(\"MODEL_CONFIG\\n\"+\"\\n\".join(model_config))\n","\n","train_imgs = img_data.loc[img_data['class']=='train']\n","val_imgs = img_data.loc[img_data['class']=='val']\n","\n","logger.info(\"Starting training scenarios.\")\n","for size in sizes:\n","  today = str(datetime.date.today())\n","  writer = SummaryWriter(os.path.join(tensorboard_dir, f\"{base_name}_{size}_{lr}_{today}\"))\n","  logger.info(\"Starting Tensorboard Summary Writer.\")\n","  logger.info(f\"Scenario {sizes.index(size)+1}: training on imageset of {img_data.shape[0]*size}\")\n","  logger.info(f\"Creating train/validation splits for {size*100}% of the imageset in an 80/20 train/val split\")\n","  if size < 1:\n","    train, _ = train_test_split(train_imgs,\n","                                test_size=size,\n","                                train_size=size,\n","                                stratify=train_imgs[['method']],\n","                                random_state=345)\n","    _, val = train_test_split(val_imgs,\n","                              test_size=size,\n","                              train_size=size,\n","                              stratify=val_imgs[['method']],\n","                              random_state=345)\n","  else:\n","    train = train_imgs.copy()\n","    val = val_imgs.copy()\n","\n","  logger.info(f\"Sampled images.\\nTraining set: {train.shape[0]} images.\\nVal set: {val.shape[0]} images\")\n","\n","  try:\n","    model_name = base_name + f\"_{size}\"\n","    model = create_model(n_classes, n_obj_det=500)\n","    # optimizer = torch.optim.SGD(model.parameters(), lr=lr, momentum=momentum)\n","    optimizer = torch.optim.Adam(model.parameters(), lr=lr)\n","    scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=gamma)\n","    if not os.path.exists(f\"./model_chkpt/{model_name}\"):\n","      os.mkdir(f\"./model_chkpt/{model_name}\")\n","  except:\n","    logger.exception('An exception occurred.')\n","\n","  # Create train dataset\n","  train_dataset = SeedDataset(image_dir=train_dir,\n","                              annot_dir=annotation_dir,\n","                              resize_dims=(resize_to, resize_to),\n","                              classes=classes,\n","                              transforms=train_transforms(),\n","                              subset=list(train['img_name'].unique()))\n","\n","  # Create val dataset\n","  val_dataset = SeedDataset(image_dir=val_dir,\n","                            annot_dir=annotation_dir,\n","                            resize_dims=(resize_to, resize_to),\n","                            classes=classes,\n","                            transforms=val_transforms(),\n","                            subset=list(val['img_name'].unique()))\n","\n","  train_loader = DataLoader(\n","    train_dataset,\n","    batch_size=batch_size,\n","    shuffle=True,\n","    num_workers=cores,\n","    collate_fn=collate_fn,\n","  )\n","\n","  val_loader = DataLoader(\n","    val_dataset,\n","    batch_size=batch_size,\n","    shuffle=False,\n","    num_workers=cores,\n","    collate_fn=collate_fn\n","  )\n","\n","  train_model(model=model,\n","              optimizer=optimizer,\n","              scheduler=scheduler,\n","              n_epochs=n_epochs,\n","              device=device,\n","              train_loader=train_loader,\n","              val_loader=val_loader,\n","              logger=logger,\n","              writer=writer,\n","              model_name=model_name)\n","\n","  writer.close()"],"metadata":{"id":"6giMzhbG0SIp","colab":{"base_uri":"https://localhost:8080/"},"outputId":"7e6ea580-4b70-4f56-df83-788f3f92acd4"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stderr","text":["2023-09-07 21:31:57,517:main_app:INFO: - MODEL_CONFIG\n","model_name:\tfasterrcnn\n","pretrained:\tTrue\n","classes:\t{'0': 'background', '1': 'split', '2': 'seed', '3': 'pod'}\n","n_classes:\t4\n","lr:\t0.01\n","momentum:\t0.9\n","n_epochs:\t50\n","batch_size:\t2\n","lr_scheduler_gamma:\t0.9\n","2023-09-07 21:31:57,520:main_app:INFO: - Starting training scenarios.\n","2023-09-07 21:31:57,527:main_app:INFO: - Starting Tensorboard Summary Writer.\n","2023-09-07 21:31:57,528:main_app:INFO: - Scenario 1: training on imageset of 500.0\n","2023-09-07 21:31:57,530:main_app:INFO: - Creating train/validation splits for 100.0% of the imageset in an 80/20 train/val split\n","2023-09-07 21:31:57,531:main_app:INFO: - Sampled images.\n","Training set: 400 images.\n","Val set: 100 images\n","2023-09-07 21:32:01,329:main_app:INFO: - Initializing training sequence\n","2023-09-07 21:32:01,331:main_app:INFO: - Epoch: 1\n","LR: [0.01]\n","Train Loss:  0.9476: 100%|██████████| 200/200 [04:06<00:00,  1.23s/it]\n","Val Loss: 0.9275: 100%|██████████| 50/50 [00:37<00:00,  1.32it/s]\n","2023-09-07 21:36:51,320:main_app:INFO: - Epoch: 2\n","LR: [0.009000000000000001]\n","Train Loss:  0.6081: 100%|██████████| 200/200 [03:40<00:00,  1.10s/it]\n","Val Loss: 0.5775: 100%|██████████| 50/50 [00:35<00:00,  1.42it/s]\n","2023-09-07 21:41:13,266:main_app:INFO: - Epoch: 3\n","LR: [0.008100000000000001]\n","Train Loss:  0.6785: 100%|██████████| 200/200 [03:40<00:00,  1.10s/it]\n","Val Loss: 0.6071: 100%|██████████| 50/50 [00:35<00:00,  1.42it/s]\n","2023-09-07 21:45:33,973:main_app:INFO: - Epoch: 4\n","LR: [0.007290000000000001]\n","Train Loss:  0.5162: 100%|██████████| 200/200 [03:44<00:00,  1.12s/it]\n","Val Loss: 0.4452: 100%|██████████| 50/50 [00:35<00:00,  1.39it/s]\n","2023-09-07 21:50:00,736:main_app:INFO: - Epoch: 5\n","LR: [0.006561000000000002]\n","Train Loss:  0.5089: 100%|██████████| 200/200 [03:41<00:00,  1.11s/it]\n","Val Loss: 0.5044: 100%|██████████| 50/50 [00:35<00:00,  1.42it/s]\n","2023-09-07 21:54:22,523:main_app:INFO: - Epoch: 6\n","LR: [0.005904900000000002]\n","Train Loss:  0.3986: 100%|██████████| 200/200 [03:40<00:00,  1.10s/it]\n","Val Loss: 0.3351: 100%|██████████| 50/50 [00:35<00:00,  1.42it/s]\n","2023-09-07 21:58:44,193:main_app:INFO: - Epoch: 7\n","LR: [0.005314410000000002]\n","Train Loss:  0.4659: 100%|██████████| 200/200 [03:48<00:00,  1.14s/it]\n","Val Loss: 0.2767: 100%|██████████| 50/50 [00:34<00:00,  1.44it/s]\n","2023-09-07 22:03:12,414:main_app:INFO: - Epoch: 8\n","LR: [0.004782969000000002]\n","Train Loss:  0.5940: 100%|██████████| 200/200 [03:41<00:00,  1.11s/it]\n","Val Loss: 0.3323: 100%|██████████| 50/50 [00:34<00:00,  1.44it/s]\n","2023-09-07 22:07:34,108:main_app:INFO: - Epoch: 9\n","LR: [0.004304672100000002]\n","Train Loss:  0.4334: 100%|██████████| 200/200 [03:45<00:00,  1.13s/it]\n","Val Loss: 0.3102: 100%|██████████| 50/50 [00:34<00:00,  1.45it/s]\n","2023-09-07 22:11:59,121:main_app:INFO: - Epoch: 10\n","LR: [0.003874204890000002]\n","Train Loss:  0.4997: 100%|██████████| 200/200 [03:37<00:00,  1.09s/it]\n","Val Loss: 0.2759: 100%|██████████| 50/50 [00:34<00:00,  1.43it/s]\n","2023-09-07 22:16:17,430:main_app:INFO: - Epoch: 11\n","LR: [0.003486784401000002]\n","Train Loss:  0.3802: 100%|██████████| 200/200 [03:43<00:00,  1.12s/it]\n","Val Loss: 0.2598: 100%|██████████| 50/50 [00:34<00:00,  1.44it/s]\n","2023-09-07 22:20:41,468:main_app:INFO: - Epoch: 12\n","LR: [0.003138105960900002]\n","Train Loss:  0.2287: 100%|██████████| 200/200 [03:43<00:00,  1.12s/it]\n","Val Loss: 0.2284: 100%|██████████| 50/50 [00:35<00:00,  1.40it/s]\n","2023-09-07 22:25:06,980:main_app:INFO: - Epoch: 13\n","LR: [0.0028242953648100018]\n","Train Loss:  0.3506: 100%|██████████| 200/200 [03:38<00:00,  1.09s/it]\n","Val Loss: 0.2234: 100%|██████████| 50/50 [00:35<00:00,  1.40it/s]\n","2023-09-07 22:29:26,156:main_app:INFO: - Epoch: 14\n","LR: [0.0025418658283290017]\n","Train Loss:  0.4054: 100%|██████████| 200/200 [03:36<00:00,  1.08s/it]\n","Val Loss: 0.2843: 100%|██████████| 50/50 [00:35<00:00,  1.41it/s]\n","2023-09-07 22:33:43,897:main_app:INFO: - Epoch: 15\n","LR: [0.0022876792454961017]\n","Train Loss:  0.3270: 100%|██████████| 200/200 [03:44<00:00,  1.12s/it]\n","Val Loss: 0.2215: 100%|██████████| 50/50 [00:35<00:00,  1.41it/s]\n","2023-09-07 22:38:08,817:main_app:INFO: - Epoch: 16\n","LR: [0.0020589113209464917]\n","Train Loss:  0.2848: 100%|██████████| 200/200 [03:45<00:00,  1.13s/it]\n","Val Loss: 0.2458: 100%|██████████| 50/50 [00:35<00:00,  1.42it/s]\n","2023-09-07 22:42:35,396:main_app:INFO: - Epoch: 17\n","LR: [0.0018530201888518425]\n","Train Loss:  0.3016: 100%|██████████| 200/200 [03:41<00:00,  1.11s/it]\n","Val Loss: 0.2625: 100%|██████████| 50/50 [00:34<00:00,  1.43it/s]\n","2023-09-07 22:46:57,371:main_app:INFO: - Epoch: 18\n","LR: [0.0016677181699666583]\n","Train Loss:  0.2737: 100%|██████████| 200/200 [03:38<00:00,  1.09s/it]\n","Val Loss: 0.2489: 100%|██████████| 50/50 [00:35<00:00,  1.40it/s]\n","2023-09-07 22:51:17,633:main_app:INFO: - Epoch: 19\n","LR: [0.0015009463529699924]\n","Train Loss:  0.2008: 100%|██████████| 200/200 [03:39<00:00,  1.10s/it]\n","Val Loss: 0.1825: 100%|██████████| 50/50 [00:35<00:00,  1.42it/s]\n","2023-09-07 22:55:38,063:main_app:INFO: - Epoch: 20\n","LR: [0.0013508517176729932]\n","Train Loss:  0.2467: 100%|██████████| 200/200 [03:39<00:00,  1.10s/it]\n","Val Loss: 0.2190: 100%|██████████| 50/50 [00:34<00:00,  1.43it/s]\n","2023-09-07 22:59:58,209:main_app:INFO: - Epoch: 21\n","LR: [0.001215766545905694]\n","Train Loss:  0.2668: 100%|██████████| 200/200 [03:35<00:00,  1.08s/it]\n","Val Loss: 0.1753: 100%|██████████| 50/50 [00:35<00:00,  1.42it/s]\n","2023-09-07 23:04:14,150:main_app:INFO: - Epoch: 22\n","LR: [0.0010941898913151245]\n","Train Loss:  0.2628: 100%|██████████| 200/200 [03:39<00:00,  1.10s/it]\n","Val Loss: 0.2141: 100%|██████████| 50/50 [00:35<00:00,  1.40it/s]\n","2023-09-07 23:08:34,918:main_app:INFO: - Epoch: 23\n","LR: [0.0009847709021836122]\n","Train Loss:  0.2227: 100%|██████████| 200/200 [03:43<00:00,  1.12s/it]\n","Val Loss: 0.2091: 100%|██████████| 50/50 [00:36<00:00,  1.38it/s]\n","2023-09-07 23:13:00,345:main_app:INFO: - Epoch: 24\n","LR: [0.0008862938119652509]\n","Train Loss:  0.2138: 100%|██████████| 200/200 [03:31<00:00,  1.06s/it]\n","Val Loss: 0.2015: 100%|██████████| 50/50 [00:34<00:00,  1.43it/s]\n","2023-09-07 23:17:12,380:main_app:INFO: - Epoch: 25\n","LR: [0.0007976644307687258]\n","Train Loss:  0.2002: 100%|██████████| 200/200 [03:44<00:00,  1.12s/it]\n","Val Loss: 0.2120: 100%|██████████| 50/50 [00:35<00:00,  1.42it/s]\n","2023-09-07 23:21:37,889:main_app:INFO: - Epoch: 26\n","LR: [0.0007178979876918532]\n","Train Loss:  0.3194: 100%|██████████| 200/200 [03:40<00:00,  1.10s/it]\n","Val Loss: 0.2068: 100%|██████████| 50/50 [00:35<00:00,  1.43it/s]\n","2023-09-07 23:25:59,569:main_app:INFO: - Epoch: 27\n","LR: [0.0006461081889226679]\n","Train Loss:  0.2346: 100%|██████████| 200/200 [03:39<00:00,  1.10s/it]\n","Val Loss: 0.2063: 100%|██████████| 50/50 [00:35<00:00,  1.42it/s]\n","2023-09-07 23:30:19,883:main_app:INFO: - Epoch: 28\n","LR: [0.0005814973700304011]\n","Train Loss:  0.3052: 100%|██████████| 200/200 [03:35<00:00,  1.08s/it]\n","Val Loss: 0.1691: 100%|██████████| 50/50 [00:35<00:00,  1.42it/s]\n","2023-09-07 23:34:36,764:main_app:INFO: - Epoch: 29\n","LR: [0.0005233476330273611]\n","Train Loss:  0.2824: 100%|██████████| 200/200 [03:33<00:00,  1.07s/it]\n","Val Loss: 0.1889: 100%|██████████| 50/50 [00:34<00:00,  1.44it/s]\n","2023-09-07 23:38:50,103:main_app:INFO: - Epoch: 30\n","LR: [0.000471012869724625]\n","Train Loss:  0.1760: 100%|██████████| 200/200 [03:43<00:00,  1.12s/it]\n","Val Loss: 0.1841: 100%|██████████| 50/50 [00:35<00:00,  1.43it/s]\n","2023-09-07 23:43:14,478:main_app:INFO: - Epoch: 31\n","LR: [0.0004239115827521625]\n","Train Loss:  0.3551: 100%|██████████| 200/200 [03:35<00:00,  1.08s/it]\n","Val Loss: 0.1844: 100%|██████████| 50/50 [00:34<00:00,  1.45it/s]\n","2023-09-07 23:47:29,874:main_app:INFO: - Epoch: 32\n","LR: [0.00038152042447694626]\n","Train Loss:  0.2116:  37%|███▋      | 74/200 [01:25<02:25,  1.16s/it]\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","Custom TB Handler failed, unregistering\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-11-5ad851e0df6a>\", line 85, in <cell line: 19>\n","    train_model(model=model,\n","  File \"/content/drive/MyDrive/github_repos/sainfoin_seed_RCNN/./src/train_val.py\", line 73, in train_model\n","  File \"/content/drive/MyDrive/github_repos/sainfoin_seed_RCNN/./src/train_val.py\", line 17, in _train\n","  File \"/usr/local/lib/python3.10/dist-packages/tqdm/std.py\", line 1182, in __iter__\n","    for obj in iterable:\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 633, in __next__\n","    data = self._next_data()\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 1345, in _next_data\n","    return self._process_data(data)\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 1371, in _process_data\n","    data.reraise()\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/_utils.py\", line 644, in reraise\n","    raise exception\n","cv2.error: Caught error in DataLoader worker process 2.\n","Original Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py\", line 308, in _worker_loop\n","    data = fetcher.fetch(index)\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py\", line 51, in fetch\n","    data = [self.dataset[idx] for idx in possibly_batched_index]\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py\", line 51, in <listcomp>\n","    data = [self.dataset[idx] for idx in possibly_batched_index]\n","  File \"/content/drive/MyDrive/github_repos/sainfoin_seed_RCNN/./src/datasets.py\", line 60, in __getitem__\n","cv2.error: OpenCV(4.8.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'\n","\n","\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-11-5ad851e0df6a>\", line 85, in <cell line: 19>\n","    train_model(model=model,\n","  File \"/content/drive/MyDrive/github_repos/sainfoin_seed_RCNN/./src/train_val.py\", line 73, in train_model\n","  File \"/content/drive/MyDrive/github_repos/sainfoin_seed_RCNN/./src/train_val.py\", line 17, in _train\n","  File \"/usr/local/lib/python3.10/dist-packages/tqdm/std.py\", line 1182, in __iter__\n","    for obj in iterable:\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 633, in __next__\n","    data = self._next_data()\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 1345, in _next_data\n","    return self._process_data(data)\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 1371, in _process_data\n","    data.reraise()\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/_utils.py\", line 644, in reraise\n","    raise exception\n","cv2.error: Caught error in DataLoader worker process 2.\n","Original Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py\", line 308, in _worker_loop\n","    data = fetcher.fetch(index)\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py\", line 51, in fetch\n","    data = [self.dataset[idx] for idx in possibly_batched_index]\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py\", line 51, in <listcomp>\n","    data = [self.dataset[idx] for idx in possibly_batched_index]\n","  File \"/content/drive/MyDrive/github_repos/sainfoin_seed_RCNN/./src/datasets.py\", line 60, in __getitem__\n","cv2.error: OpenCV(4.8.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'\n","\n","\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 1972, in wrapped\n","    stb = handler(self,etype,value,tb,tb_offset=tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/dask/base.py\", line 79, in _clean_ipython_traceback\n","    stb = self.InteractiveTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-11-5ad851e0df6a>\", line 85, in <cell line: 19>\n","    train_model(model=model,\n","  File \"/content/drive/MyDrive/github_repos/sainfoin_seed_RCNN/./src/train_val.py\", line 73, in train_model\n","  File \"/content/drive/MyDrive/github_repos/sainfoin_seed_RCNN/./src/train_val.py\", line 17, in _train\n","  File \"/usr/local/lib/python3.10/dist-packages/tqdm/std.py\", line 1182, in __iter__\n","    for obj in iterable:\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 633, in __next__\n","    data = self._next_data()\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 1345, in _next_data\n","    return self._process_data(data)\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 1371, in _process_data\n","    data.reraise()\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/_utils.py\", line 644, in reraise\n","    raise exception\n","cv2.error: Caught error in DataLoader worker process 2.\n","Original Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py\", line 308, in _worker_loop\n","    data = fetcher.fetch(index)\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py\", line 51, in fetch\n","    data = [self.dataset[idx] for idx in possibly_batched_index]\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py\", line 51, in <listcomp>\n","    data = [self.dataset[idx] for idx in possibly_batched_index]\n","  File \"/content/drive/MyDrive/github_repos/sainfoin_seed_RCNN/./src/datasets.py\", line 60, in __getitem__\n","cv2.error: OpenCV(4.8.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'\n","\n","\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 1972, in wrapped\n","    stb = handler(self,etype,value,tb,tb_offset=tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/dask/base.py\", line 79, in _clean_ipython_traceback\n","    stb = self.InteractiveTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3571, in run_code\n","    self.CustomTB(etype, value, tb)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 1979, in wrapped\n","    stb = self.InteractiveTB.structured_traceback(*sys.exc_info())\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-11-5ad851e0df6a>\", line 85, in <cell line: 19>\n","    train_model(model=model,\n","  File \"/content/drive/MyDrive/github_repos/sainfoin_seed_RCNN/./src/train_val.py\", line 73, in train_model\n","  File \"/content/drive/MyDrive/github_repos/sainfoin_seed_RCNN/./src/train_val.py\", line 17, in _train\n","  File \"/usr/local/lib/python3.10/dist-packages/tqdm/std.py\", line 1182, in __iter__\n","    for obj in iterable:\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 633, in __next__\n","    data = self._next_data()\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 1345, in _next_data\n","    return self._process_data(data)\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py\", line 1371, in _process_data\n","    data.reraise()\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/_utils.py\", line 644, in reraise\n","    raise exception\n","cv2.error: Caught error in DataLoader worker process 2.\n","Original Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py\", line 308, in _worker_loop\n","    data = fetcher.fetch(index)\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py\", line 51, in fetch\n","    data = [self.dataset[idx] for idx in possibly_batched_index]\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py\", line 51, in <listcomp>\n","    data = [self.dataset[idx] for idx in possibly_batched_index]\n","  File \"/content/drive/MyDrive/github_repos/sainfoin_seed_RCNN/./src/datasets.py\", line 60, in __getitem__\n","cv2.error: OpenCV(4.8.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'\n","\n","\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 1972, in wrapped\n","    stb = handler(self,etype,value,tb,tb_offset=tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/dask/base.py\", line 79, in _clean_ipython_traceback\n","    stb = self.InteractiveTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3571, in run_code\n","    self.CustomTB(etype, value, tb)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 1979, in wrapped\n","    stb = self.InteractiveTB.structured_traceback(*sys.exc_info())\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}]},{"cell_type":"code","source":["loss_dict = {'loss_classifier': torch.Tensor([0.1050]), 'loss_box_reg': torch.Tensor([0.1940]), 'loss_objectness': torch.Tensor([6.9332e-05]), 'loss_rpn_box_reg': torch.Tensor([0.0159])}\n","loss = sum(i for i in loss_dict.values())\n","print(loss)\n","loss = torch.mean(torch.Tensor([i for i in loss_dict.values()]))\n","print(loss)"],"metadata":{"id":"LQNRt3_HDzEa","executionInfo":{"status":"ok","timestamp":1694130535978,"user_tz":240,"elapsed":20,"user":{"displayName":"Bo Meyering","userId":"12820085305614794448"}},"colab":{"base_uri":"https://localhost:8080/"},"outputId":"eb19c148-4e26-4e60-dd9b-2d0e577b96b5"},"execution_count":11,"outputs":[{"output_type":"stream","name":"stdout","text":["tensor([0.3150])\n","tensor(0.0787)\n"]}]},{"cell_type":"code","source":["torch.Tensor([34.5])"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"ajfV9mhfN5mx","executionInfo":{"status":"ok","timestamp":1694130535980,"user_tz":240,"elapsed":10,"user":{"displayName":"Bo Meyering","userId":"12820085305614794448"}},"outputId":"0de318d8-b1f3-4274-d305-fdbf8ad7bfe1"},"execution_count":12,"outputs":[{"output_type":"execute_result","data":{"text/plain":["tensor([34.5000])"]},"metadata":{},"execution_count":12}]}]}